diffblue/cover-github-action

- package-lock.json
- package.json
See: https://stackoverflow.com/questions/76624993/prettier-3-0-0-typeerror-prettier-resolveconfig-sync-is-not-a-function
> Bump prettier to 3.0.1 & eslint-plugin-prettier 5.0.0 in tandem

- .github/workflows/Test.yml
- README.md
Change from `DIFFBLUE_TOKEN` to `DIFFBLUE_ACCESS_TOKEN` to match with gitlab.
> [TG-21024]Update env variable for access token to DIFFBLUE_ACCESS_TOKEN

- README.md
Default JDK is 17, so have README example use Java 17
> Align readme and default

- .github/workflows/Test.yml
- README.md
Remove DIFFBLUE_ACCESS_TOKEN at checkout
Remove GITHUB_PR_NUMBER
> [TG-21006]More Action release prep

- README.md
Add comments to the REAMDE example workflow to better explain how the action handles args.
> Improve action arg clarity in README

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.04.02
> Release 2024.04.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.05.01
> Release 2024.05.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.05.02
> Release 2024.05.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.06.01
> Release 2024.06.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.06.02
> Release 2024.06.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.07.01
> Release 2024.07.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.07.03
> Release 2024.07.03

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.08.02
> Release 2024.08.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.09.01
> Release 2024.09.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.09.02
> Release 2024.09.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.10.01
> Release 2024.10.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.10.02
> Release 2024.10.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.11.01
> Release 2024.11.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.11.02
> Release 2024.11.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.12.01
> Release 2024.12.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2024.12.02
> Release 2024.12.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.01.01
> Release 2025.01.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.01.02
> Release 2025.01.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.02.01
> Release 2025.02.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.02.02
> Release 2025.02.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.03.01
> Release 2025.03.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.03.02
> Release 2025.03.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.04.01
> Release 2025.04.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.04.02
> Release 2025.04.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.05.01
> Release 2025.05.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.05.02
> Release 2025.05.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.06.02
> Release 2025.06.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.07.02
> Release 2025.07.02

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.08.01
> Release 2025.08.01

- Dockerfile
- jdk11/Dockerfile
- jdk17/Dockerfile
- jdk21/Dockerfile
- jdk8/Dockerfile
Update Diffblue Cover to 2025.09.01
> Release 2025.09.01
